/** Which procedural visual represents the project on its card and case-study hero. */
export type ProjectVisual = 'kl' | 'lorenz' | 'stars' | 'attention' | 'loss' | 'flow' | 'voronoi'

/** The branch of mathematics a project grows from (its branch on the project tree). */
export type Field = 'information' | 'probability' | 'linear' | 'optimization' | 'dynamics' | 'graphs'
export const fields: Record<Field, { label: string; eq: string }> = {
  information: { label: 'Information Theory', eq: 'H(X) = -\\sum p \\log p' },
  probability: { label: 'Probability', eq: 'p(y \\mid x)' },
  linear: { label: 'Linear Algebra', eq: 'A\\mathbf{v} = \\lambda \\mathbf{v}' },
  optimization: { label: 'Optimization', eq: '\\nabla \\mathcal{L} = 0' },
  dynamics: { label: 'Dynamical Systems', eq: '\\dot{x} = f(x)' },
  graphs: { label: 'Graph Theory', eq: 'G = (V, E)' },
}

export interface Project {
  slug: string
  title: string
  summary: string
  body: string[]
  org: string
  year: string
  tags: string[]
  stack: string[]
  features: string[]
  challenges: string[]
  image?: string
  visual: ProjectVisual
  field: Field
  /** Optional optimised GLB in /models shown as the case-study hero. */
  model?: string
  /** One equation (TeX) that captures the idea — rendered as typography. */
  equation: string
  featured?: boolean
  links: { github?: string; demo?: string; report?: string }
}

export const projects: Project[] = [
  {
    slug: 'agentic-service-platform',
    title: 'Agentic Service Platform',
    summary: 'A Claude-powered multi-agent platform at Ricoh. An orchestrator routes each request to a Data Analyst agent or a Service agent that helps field technicians fix printers.',
    body: [
      'An orchestrator reads each request and hands it to the right specialist: a Data Analyst agent for questions about the data, or a Service agent that retrieves maintenance documentation and walks a field technician through diagnosing and fixing a printer.',
      'The Service agent shows the matching procedural illustration next to each repair step. It remembers the conversation, learns from human feedback, and can call JIRA and Redmine through AWS connectors.',
    ],
    org: 'Ricoh',
    year: '2025 to now',
    tags: ['Agents', 'Claude', 'Tool calling'],
    stack: ['Claude', 'Python', 'AWS Lambda', 'DynamoDB', 'S3', 'Aurora SQL'],
    features: ['Orchestrator that routes between specialist agents', 'Service agent grounded in maintenance documentation', 'Step-by-step guidance with procedural illustrations', 'Conversational memory, human feedback, JIRA and Redmine tools'],
    challenges: ['Routing ambiguous requests to the right agent', 'Grounding answers in long technical manuals', 'Designing an AWS base that later agents can reuse'],
    visual: 'attention',
    field: 'graphs',
    equation: 'a^{*} = \\arg\\max_{i}\\; p(\\text{agent}_i \\mid q)',
    links: {},
  },
  {
    slug: 'ray-document-pipeline',
    title: 'Document Pipeline on Ray',
    summary: 'A parallel ingestion pipeline on Ray that processes thousands of documents in under an hour.',
    body: [
      'Documents are split into tasks that Ray schedules across a pool of workers, so parsing, chunking and embedding run in parallel instead of one file at a time.',
      'The whole corpus, thousands of documents, now goes through in under an hour.',
    ],
    org: 'Ricoh',
    year: '2026',
    tags: ['Data', 'Parallelism', 'Ray'],
    stack: ['Python', 'Ray', 'AWS S3'],
    features: ['Task graph scheduled across many workers', 'Parsing, chunking and embedding in parallel', 'Thousands of documents in under an hour'],
    challenges: ['Balancing very uneven document sizes', 'Keeping memory steady across long runs', 'Retrying failed tasks without redoing finished work'],
    visual: 'flow',
    field: 'graphs',
    equation: 'S(n) = \\frac{1}{(1-p) + p/n}',
    links: {},
  },
  {
    slug: 'ui-snapshot-harness',
    title: 'Localized UI Snapshot Harness',
    summary: 'An agentic harness that captures 130 app screens in each of 7 languages, turning 60 hours of manual work into 40 minutes.',
    body: [
      'Every release needs screenshots of the same screens in every supported language. An agent now walks the app screen by screen, switches language and captures each state.',
      'It produces 900+ images per run (130 screens in each of 7 languages), in about 40 minutes instead of 60 hours by hand.',
    ],
    org: 'Ricoh',
    year: '2026',
    tags: ['Agents', 'Automation', 'Localization'],
    stack: ['Python', 'Claude', 'UI automation'],
    features: ['Agent navigates the app as a graph of screens', '7 languages, 130 screens each, 900+ images', '60 hours of manual work down to 40 minutes'],
    challenges: ['Reaching deep screens reliably', 'Text that grows or wraps differently per language', 'Making runs repeatable from release to release'],
    visual: 'voronoi',
    field: 'graphs',
    equation: '130 \\times 7 \\geq 900,\\quad 60\\,\\mathrm{h} \\to 40\\,\\mathrm{min}',
    links: {},
  },
  {
    slug: 'rag-architecture',
    title: 'RAG at Scale',
    summary: 'A RAG system on vLLM serving millions of customers. Hybrid retrieval with reranker fusion cut latency by 20% and hallucinations by 35%.',
    body: [
      'A production RAG system that accepts text, images and structured data, retrieves with a hybrid lexical and dense index, and fuses the results with a reranker before generating a grounded answer.',
      'vLLM and careful caching keep it fast at that scale. Compared with the first version, response latency dropped by 20% and hallucinations by 35%.',
    ],
    org: 'ZOHO',
    year: '2023 to 2024',
    tags: ['LLM', 'RAG', 'vLLM'],
    stack: ['Python', 'vLLM', 'PyTorch', 'FastAPI', 'Redis', 'PostgreSQL'],
    features: ['Multimodal input: text, images, structured data', 'Hybrid retriever and reranker fusion', '20% lower latency, 35% fewer hallucinations', 'Serves millions of customers'],
    challenges: ['Inference speed vs. answer quality', 'Caching for frequent queries', 'Concurrency at scale', 'Hallucination reduction via context-aware filtering'],
    image: 'rag',
    visual: 'attention',
    field: 'probability',
    equation: 'p(y\\mid x)=\\sum_{z\\in\\text{top-}k} p_\\eta(z\\mid x)\\,p_\\theta(y\\mid x,z)',
    featured: true,
    links: {},
  },
  {
    slug: 'kl-divergence',
    title: 'KL Divergence: A Statistical Bridge',
    summary: 'Showing with real models that maximum likelihood and KL minimisation are the same thing. Logistic regression, random forests, neural nets and VAEs, all visualised live.',
    body: [
      'A study of the relationship between maximum likelihood estimation and KL-divergence minimisation across model families, with real-time visualisation of the divergence as models train.',
      'It extends to Variational Autoencoders, showing how the KL term regularises the latent space.',
    ],
    org: 'University of Colorado',
    year: '2024',
    tags: ['Statistics', 'Deep Learning', 'VAE'],
    stack: ['Python', 'PyTorch', 'scikit-learn', 'React'],
    features: ['Live KL tracking during training', 'Side-by-side model families', 'Interactive distribution explorer', 'VAE latent-space visualisation'],
    challenges: ['Real-time visualisation of training metrics', 'Consistent distribution matching across models', 'Making statistical ideas intuitive'],
    image: 'KL',
    visual: 'kl',
    field: 'information',
    equation: 'D_{\\mathrm{KL}}(P\\,\\|\\,Q)=\\sum_x P(x)\\log\\frac{P(x)}{Q(x)}',
    featured: true,
    links: { github: 'https://github.com/Arsive02/KL_divergence_statistics', demo: 'https://kl-divergence-statistics.vercel.app', report: '/docs/KL.pdf' },
  },
  {
    slug: 'stellar-mapping',
    title: 'Stellar Mapping',
    summary: 'Finding constellations in night-sky photos with an ensemble of a CNN, a Vision Transformer and EfficientNet. It holds up under light pollution and rotation.',
    body: [
      'An ensemble of CNNs, Vision Transformers and EfficientNet that identifies constellations in astronomical images under varying observational conditions.',
      'A custom augmentation pipeline handles star brightness, atmospheric noise, rotation and multi-scale patterns.',
    ],
    org: 'University of Colorado',
    year: '2024',
    tags: ['Computer Vision', 'Astronomy', 'Ensembles'],
    stack: ['Python', 'PyTorch', 'ViT', 'EfficientNet'],
    features: ['CNN + ViT + EfficientNet ensemble', 'Robust to lighting and light pollution', 'Astronomy-specific augmentation', 'Real-time detection'],
    challenges: ['Varying star brightness', 'Rotation-invariant recognition', 'Multi-scale patterns'],
    image: 'stellar',
    visual: 'stars',
    field: 'probability',
    model: '/models/telescope.glb',
    equation: '\\hat y=\\arg\\max_c \\tfrac{1}{M}\\sum_{m=1}^{M} p_m(c\\mid x)',
    featured: true,
    links: { github: 'https://github.com/rahul7310/stellar_mapping', demo: 'https://stellarmapping.vercel.app/', report: '/docs/Stellar_Mapping_Report.pdf' },
  },
  {
    slug: 'mamba-transformer',
    title: 'Mamba × Transformer Hybrid',
    summary: 'Mamba handles long-range memory and attention handles focus. I tried running them side by side, one after the other, and with a learned switch between them.',
    body: [
      'An experimental hybrid that pairs Mamba’s selective state-space layers (efficient long-range dependencies) with Transformer attention (precise focus on key tokens).',
      'Ablations compare parallel, cascaded and adaptive-switching integration strategies across sequence lengths, trading compute, memory and quality.',
    ],
    org: 'ZOHO',
    year: '2024',
    tags: ['Architecture', 'SSM', 'Transformers'],
    stack: ['Python', 'PyTorch', 'Mamba SSM', 'JAX', 'W&B'],
    features: ['Hybrid SSM + attention blocks', 'Adaptive routing between mechanisms', 'Efficient long-sequence processing', 'Full ablation study'],
    challenges: ['Balancing compute across components', 'Memory for long sequences', 'Stable training of the hybrid'],
    image: 'mamba',
    visual: 'flow',
    field: 'dynamics',
    equation: 'h_t=\\bar A h_{t-1}+\\bar B x_t,\\quad y_t=C h_t',
    featured: true,
    links: {},
  },
  {
    slug: 'goodreads-t5',
    title: 'Goodreads Rating Prediction, 1st Place',
    summary: 'Won a Kaggle competition by treating rating prediction as a text generation problem.',
    body: [
      'Instead of training a classifier, I fine-tuned T5 to write out the 0 to 5 rating from the review text and book details, with custom preprocessing. It reached 0.70 mean F1, beat the classification baselines and took first place.',
    ],
    org: 'Kaggle',
    year: '2022 to 2023',
    tags: ['NLP', 'T5', 'Kaggle'],
    stack: ['Python', 'PyTorch', 'Transformers', 'Pandas'],
    features: ['Generative model for a classification task', 'Text + metadata pipeline', 'First place on the leaderboard'],
    challenges: ['Adapting a generative model to classification', 'Large-scale review data', 'Competition compute limits'],
    image: 'goodreads',
    visual: 'loss',
    field: 'optimization',
    equation: '\\mathcal{L}=-\\sum_t \\log p_\\theta(y_t\\mid y_{<t},x)',
    featured: true,
    links: { github: 'https://github.com/Arsive02/Goodreads_Books_Review_Rating_Prediction', demo: 'https://www.kaggle.com/competitions/goodreads-books-reviews-290312/leaderboard' },
  },
  {
    slug: 'paligemma-invoice',
    title: 'Invoice → JSON with PaliGemma',
    summary: 'A fine-tuned PaliGemma that reads invoices in 200+ different layouts and returns clean, validated JSON, with 88% of fields right.',
    body: ['A document-understanding pipeline: pre-processing, a fine-tuned PaliGemma, and schema validation that repairs malformed output across diverse invoice layouts.'],
    org: 'ZOHO',
    year: '2024',
    tags: ['Document AI', 'VLM', 'Fine-tuning'],
    stack: ['Python', 'PaliGemma', 'PyTorch', 'FastAPI'],
    features: ['Invoice-specific fine-tuning', 'Contextual field extraction', 'Automatic JSON schema validation'],
    challenges: ['Diverse layouts', 'Efficient VLM fine-tuning', 'Low-quality scans'],
    image: 'PaliGemma',
    visual: 'voronoi',
    field: 'optimization',
    equation: '\\theta^*=\\arg\\min_\\theta\\,\\mathbb{E}_{(I,j)}\\big[-\\log p_\\theta(j\\mid I)\\big]',
    links: { github: 'https://huggingface.co/Arsive/paligemma-img-to-json/tree/main', demo: 'https://huggingface.co/Arsive/paligemma-img-to-json' },
  },
  {
    slug: 'rlhf-dpo',
    title: 'RLHF with DPO',
    summary: 'Comparing Direct Preference Optimisation with classic RLHF on a real RAG system: how stable training is, how fast it converges, and how good the answers get.',
    body: ['An implementation and comparison of DPO against PPO-style RLHF, measuring training stability, convergence and output quality when aligning a RAG generator.'],
    org: 'ZOHO',
    year: '2024',
    tags: ['Alignment', 'RLHF', 'DPO'],
    stack: ['Python', 'PyTorch', 'Transformers', 'Ray', 'W&B'],
    features: ['DPO implementation', 'Preference-learning experiments', 'Head-to-head with RLHF'],
    challenges: ['Efficient preference learning', 'Compute for large-scale training', 'Reliable evaluation'],
    image: 'rlhf',
    visual: 'loss',
    field: 'optimization',
    equation: '-\\log\\sigma\\!\\Big(\\beta\\log\\tfrac{\\pi_\\theta(y_w)}{\\pi_{\\text{ref}}(y_w)}-\\beta\\log\\tfrac{\\pi_\\theta(y_l)}{\\pi_{\\text{ref}}(y_l)}\\Big)',
    links: {},
  },
  {
    slug: 'roberta-toxicity',
    title: 'RoBERTa Toxicity Classifier',
    summary: 'Flags hate, obscenity, threats and insults in text, tuned to avoid false alarms in real moderation work.',
    body: ['RoBERTa fine-tuned for multi-label toxicity with attention to ambiguous and context-dependent content, balancing recall against false positives.'],
    org: 'Personal',
    year: '2024',
    tags: ['NLP', 'Classification'],
    stack: ['Python', 'PyTorch', 'Hugging Face'],
    features: ['Multi-label classification', 'Precision/recall balancing', 'Real-time inference'],
    challenges: ['False positives', 'Cultural and contextual nuance', 'Model size vs. quality'],
    image: 'roberta',
    visual: 'attention',
    field: 'linear',
    equation: '\\mathrm{softmax}\\!\\left(\\frac{QK^\\top}{\\sqrt{d_k}}\\right)V',
    links: { github: 'https://huggingface.co/Arsive/roberta-toxicity-classifier/tree/main', demo: 'https://huggingface.co/Arsive/roberta-toxicity-classifier' },
  },
  {
    slug: 'resume-parser',
    title: 'Resume Parser with OCR',
    summary: 'OCR + NER pipeline that extracts and normalises entities and ambiguous dates from any resume format.',
    body: ['A pipeline that cleans up the document, runs Surya OCR, pulls out the entities and checks them, with extra care for vague or relative dates.'],
    org: 'ZOHO',
    year: '2024',
    tags: ['NLP', 'OCR', 'IE'],
    stack: ['Python', 'Surya OCR', 'spaCy', 'Flask'],
    features: ['PDF / DOCX / image support', 'Date normalisation', 'Section classification'],
    challenges: ['Heterogeneous layouts', 'Date ambiguity', 'Robust section detection'],
    image: 'resume_parsing',
    visual: 'voronoi',
    field: 'probability',
    equation: 'P(\\mathbf{y}\\mid\\mathbf{x})\\propto\\exp\\Big(\\sum_t \\psi(y_{t-1},y_t,\\mathbf{x})\\Big)',
    links: { github: 'https://github.com/VikParuchuri/surya' },
  },
  {
    slug: 'multimodal-system',
    title: 'Multimodal AI System',
    summary: 'Speech, text, images and video in one system, used for meeting summaries, scene detection and search across formats.',
    body: ['Whisper, CLIP and TimeSformer unified with cross-modal attention and temporal alignment. Results were mixed across modalities, and it taught me more than most of my successes.'],
    org: 'ZOHO',
    year: '2023 to 2024',
    tags: ['Multimodal', 'Video', 'Speech'],
    stack: ['Python', 'PyTorch', 'Whisper', 'CLIP', 'TimeSformer'],
    features: ['Speech-to-text summarisation', 'Video scene segmentation', 'Cross-modal retrieval'],
    challenges: ['Temporal synchronisation', 'Memory for concurrent models', 'Uneven quality across modalities'],
    image: 'multi',
    visual: 'flow',
    field: 'linear',
    equation: '\\mathcal{L}_{\\text{CLIP}}=-\\log\\frac{e^{\\langle u_i,v_i\\rangle/\\tau}}{\\sum_j e^{\\langle u_i,v_j\\rangle/\\tau}}',
    links: {},
  },
  {
    slug: 'edge-aiot',
    title: 'Edge AIoT Inspection',
    summary: 'A full-stack inspection system (CNN, Flask, DynamoDB, Raspberry Pi) that spots defective microchips in real time with 98% accuracy.',
    body: ['An automated quality-control station that classifies defective microchips at the edge, with a web dashboard and automated reports.'],
    org: 'Sri Sai Ram Engineering College',
    year: '2021',
    tags: ['IoT', 'Edge ML', 'AWS'],
    stack: ['Python', 'TensorFlow', 'OpenCV', 'Flask', 'DynamoDB', 'Raspberry Pi'],
    features: ['98% accurate real-time defect detection', 'Cloud logging to DynamoDB', 'Monitoring dashboard'],
    challenges: ['Limited labelled data', 'Inference on constrained hardware', 'Lighting variation'],
    image: 'edge',
    visual: 'voronoi',
    field: 'optimization',
    equation: '\\min_{w,b}\\ \\tfrac12\\|w\\|^2\\ \\text{s.t.}\\ y_i(w^\\top x_i+b)\\ge 1',
    links: { demo: 'https://www.youtube.com/watch?v=mOJEEJ-eYmM' },
  },
  {
    slug: 'autonomous-vehicle',
    title: 'Autonomous Ground Vehicle',
    summary: 'A small robot that follows lanes, dodges obstacles with YOLOv4 and plans its own path on a Jetson Nano.',
    body: ['A ground robot with lane detection, YOLOv4 object detection and custom path planning, optimised for embedded GPUs.'],
    org: 'Sri Sai Ram Engineering College',
    year: '2019 to 2022',
    tags: ['Robotics', 'Computer Vision', 'YOLO'],
    stack: ['Python', 'YOLOv4', 'ROS', 'OpenCV', 'Jetson Nano'],
    features: ['Real-time lane tracking', 'Obstacle avoidance', 'Remote monitoring'],
    challenges: ['Lane detection in varied conditions', 'YOLO on edge devices', 'Sensor integration'],
    image: 'agv',
    visual: 'lorenz',
    field: 'dynamics',
    equation: '\\dot x=\\sigma(y-x),\\ \\dot y=x(\\rho-z)-y,\\ \\dot z=xy-\\beta z',
    links: { github: 'https://github.com/Balaji-th/Autonomous_Vehicle', demo: 'https://youtu.be/48irckF3vA0' },
  },
]

export const projectBySlug = (slug: string) => projects.find((p) => p.slug === slug)
